local teams = {
    "3dm", "ad", "amka", "apex", "astr", "avg", "big", "bne", "bravg", "c9",
    "c9g", "clg", "cm", "col", "cope", "cplx", "cr4z", "cw", "dat", "dh13aa",
    "dh13ab", "dig", "drea", "e6ten", "ebet", "ecst", "ence", "ent", "eps",
    "esc", "eter", "evl", "faze", "flg", "flip", "flux", "fntc", "forz", "fq",
    "furi", "g2", "gamb", "gl", "god", "gray", "hero", "hlr", "ibp", "ihc",
    "im", "imp", "imt", "index", "indw", "intz", "itb", "keyd", "king", "koi",
    "lc", "ldlc", "lgb", "lgcy", "liq", "lumi", "lumik", "lynn", "mfg", "mibr",
    "mngz", "mont", "mouz", "mss", "myxmg", "navi", "nein", "nf", "nine", "nip",
    "nipta", "niptb", "nologo", "nor", "nosticker", "nrg", "nv", "og", "optc",
    "orbit", "out", "package", "pain", "pand", "penta", "pkd", "psnu", "qb",
    "r", "ratm", "ren", "rgg", "ride", "rog", "saw", "shrk", "sk", "spc", "spir",
    "splc", "spr", "steu", "stus", "syma", "thv", "tit", "tsm", "tsolo", "tyl",
    "us", "v", "v2", "ve", "vega", "vex", "vg", "vici", "vita", "vp", "wcrd",
    "wgg", "wins", "xapso", "zzn"
}
local teamsName = {
    ["3dm"] = "3DMAX",
    ["ad"] = "Astro Disciples",
    ["amka"] = "AMKAL",
    ["apex"] = "Apeks",
    ["astr"] = "Astralis",
    ["avg"] = "Avangar",
    ["big"] = "BIG",
    ["bne"] = "Bad News Eagles",
    ["bravg"] = "Bravado Gaming",
    ["c9"] = "Cloud9",
    ["c9g"] = "Cloud9 Gaming",
    ["clg"] = "Counter Logic Gaming",
    ["cm"] = "Copenhagen Wolves",
    ["col"] = "Complexity Gaming",
    ["cope"] = "Copenhagen Flames",
    ["cplx"] = "Complexity",
    ["cr4z"] = "CR4ZY",
    ["cw"] = "Copenhagen Wolves",
    ["dat"] = "Danish Allstars Team",
    ["dh13aa"] = "DreamHack 2013 A",
    ["dh13ab"] = "DreamHack 2013 B",
    ["dig"] = "Dignitas",
    ["drea"] = "DreamEaters",
    ["e6ten"] = "E6TEN",
    ["ebet"] = "Ebet Gaming",
    ["ecst"] = "ECSTATIC",
    ["ence"] = "ENCE",
    ["ent"] = "EnVy",
    ["eps"] = "Epsilon Esports",
    ["esc"] = "ESC Gaming",
    ["eter"] = "Eternal Fire",
    ["evl"] = "Evil Geniuses",
    ["faze"] = "FaZe Clan",
    ["flg"] = "Flipsid3 Gaming",
    ["flip"] = "FlipSid3 Tactics",
    ["flux"] = "Fluxo",
    ["fntc"] = "Fnatic",
    ["forz"] = "forZe",
    ["fq"] = "Fragsters",
    ["furi"] = "FURIA Esports",
    ["g2"] = "G2 Esports",
    ["gamb"] = "Gambit Esports",
    ["gl"] = "GamerLegion",
    ["god"] = "Godsent",
    ["gray"] = "Grayhound Gaming",
    ["hero"] = "Heroic",
    ["hlr"] = "HellRaisers",
    ["ibp"] = "iBUYPOWER",
    ["ihc"] = "IHC Esports",
    ["im"] = "Imperial",
    ["imp"] = "Imperial Esports",
    ["imt"] = "Immortals",
    ["index"] = "Index Gaming",
    ["indw"] = "Indigo Wolves",
    ["intz"] = "INTZ Esports",
    ["itb"] = "Into the Breach",
    ["keyd"] = "Keyd Stars",
    ["king"] = "Kinguin",
    ["koi"] = "KOI Esports",
    ["lc"] = "London Conspiracy",
    ["ldlc"] = "LDLC OL",
    ["lgb"] = "LGB Esports",
    ["lgcy"] = "Legacy Esports",
    ["liq"] = "Team Liquid",
    ["lumi"] = "Luminosity Gaming",
    ["lumik"] = "Luminosity Kids",
    ["lynn"] = "Lynn Vision Gaming",
    ["mfg"] = "MyFrag Gaming",
    ["mibr"] = "MIBR",
    ["mngz"] = "Mongolz",
    ["mont"] = "Monte",
    ["mouz"] = "MOUZ",
    ["mss"] = "Missing Esports",
    ["myxmg"] = "myXMG",
    ["navi"] = "Natus Vincere",
    ["nein"] = "Nine Esports",
    ["nf"] = "NoFear Gaming",
    ["nine"] = "9INE",
    ["nip"] = "Ninjas in Pyjamas",
    ["nipta"] = "NiP Talent A",
    ["niptb"] = "NiP Talent B",
    ["nologo"] = "No Logo Team",
    ["nor"] = "North",
    ["nosticker"] = "No Sticker Team",
    ["nrg"] = "NRG Esports",
    ["nv"] = "Team EnVy",
    ["og"] = "OG Esports",
    ["optc"] = "OpTic Gaming",
    ["orbit"] = "Orbit Esports",
    ["out"] = "Outsiders",
    ["package"] = "The Package",
    ["pain"] = "paiN Gaming",
    ["pand"] = "Panda Gaming",
    ["penta"] = "PENTA Sports",
    ["pkd"] = "Planetkey Dynamics",
    ["psnu"] = "PS Nuova",
    ["qb"] = "Quantum Bellator Fire",
    ["r"] = "Raptors",
    ["ratm"] = "RATM Gaming",
    ["ren"] = "Renegades",
    ["rgg"] = "Rogue Gaming",
    ["ride"] = "Riders Esports",
    ["rog"] = "Rogue",
    ["saw"] = "SAW Esports",
    ["shrk"] = "Sharks Esports",
    ["sk"] = "SK Gaming",
    ["spc"] = "Space Soldiers",
    ["spir"] = "Spirit",
    ["splc"] = "Splice Gaming",
    ["spr"] = "Sprout",
    ["steu"] = "SteelSeries Europe",
    ["stus"] = "SteelSeries US",
    ["syma"] = "Syman Gaming",
    ["thv"] = "TheVikings",
    ["tit"] = "Titan",
    ["tsm"] = "TSM",
    ["tsolo"] = "Team SoloMid",
    ["tyl"] = "Tyloo",
    ["us"] = "United States Esports",
    ["v"] = "Vitality",
    ["v2"] = "Version2",
    ["ve"] = "Vexed Gaming",
    ["vega"] = "Vega Squadron",
    ["vex"] = "Vexed Esports",
    ["vg"] = "Vici Gaming",
    ["vici"] = "ViCi Esports",
    ["vita"] = "Team Vitality",
    ["vp"] = "Virtus.pro",
    ["wcrd"] = "Wildcard Gaming",
    ["wgg"] = "WG Gaming",
    ["wins"] = "Winstrike Team",
    ["xapso"] = "Xapso",
    ["zzn"] = "ZZN Esports"
}

local random = math.random

AddEventHandler("OnMapLoad", function(event)
    local random_1 = random(1, #teams)
    server:Execute("mp_teamlogo_1 " .. teams[random_1])
    server:Execute("mp_teamname_1 " .. teamsName[random_1])
    local random_2 = random(1, #teams)
    server:Execute("mp_teamlogo_2 " .. teams[random_2])
    server:Execute("mp_teamname_2 " .. teamsName[random_2])
end)
