local teams = {
    "zzn",  "thv", "3dm", "nein", "pand", "nine", "amka", "apex", "ad", "astr", "avg", "bne", "big", "bravg", "cm", "c9", "col",
    "cope", "cw", "clg", "cr4z", "dat", "dig", "drea", "ebet", "ecst", "ence", "ent", "nv", "eps", "esc", "eter", "evl", "faze",
    "flg", "flip", "flux", "fq", "fntc", "forz", "furi", "g2", "gamb", "gl", "god", "gray", "hlr", "hero", "ibp", "ihc", "imt",
    "im", "imp", "itb", "intz", "keyd", "king", "koi", "ldlc", "lgcy", "lgb", "liq", "lc", "lumi", "lynn", "mibr", "mfg", "mngz",
    "mont", "mss", "mouz", "ride", "myxmg", "nf", "navi", "nip", "nor", "nrg", "og", "optc", "orbit", "out", "pain", "psnu", "penta",
    "pkd", "qb", "ratm", "rgg", "wgg", "ren", "rog", "saw", "shrk", "sk", "spc", "spir", "splc", "spr", "syma", "tsm", "tit", "tyl",
    "us", "vega", "vg", "vex", "vici", "vp", "vita", "ve", "wins", "wcrd", "indw", "e6ten", "xapso"
}
local teamsName = {
    ["zzn"] = "00 Nation",
    ["thv"] = "100 Thieves",
    ["3dm"] = "3DMAX",
    ["nein"] = "9INE",
    ["pand"] = "9Pandas",
    ["nine"] = "9z Team",	
    ["amka"] = "AMKAL ESPORTS",
    ["apex"] = "Apeks",
    ["ad"] = "Astana Dragons",
    ["astr"] = "Astralis",
    ["avg"] = "Avangar",
    ["bne"] = "Bad News Eagles",
    ["big"] = "BIG",
    ["bravg"] = "Bravado Gaming",
    ["cm"] = "Clan-Mystik",
    ["c9"] = "Cloud9",
    ["col"] = "compLexity Gaming",
    ["cope"] = "Copenhagen Flames",
    ["cw"] = "Copenhagen Wolves",
    ["clg"] = "Counter Logic Gaming"
    ["cr4z"] = "CR4ZY",	
    ["dat"] = "dAT Team",
    ["dig"] = "Team Dignitas",
    ["drea"] = "DreamEaters",
    ["ebet"] = "Team eBettle",
    ["ecst"] = "ECSTATIC",
    ["ence"] = "ENCE eSports",
    ["ent"] = "EntropiqTeam EnVyUs",
    ["nv"] = "Team EnVyUs",
    ["eps"] = "Epsilon eSports",
    ["esc"] = "ESC Gaming",
    ["eter"] = "Eternal Fire",
    ["evl"] = "Evil Geniuses",
    ["faze"] = "FaZe Clan",
    ["flg"] = "Flash Gaming",
    ["flip"] = "Flipsid3 Tactics",
    ["flux"] = "Fluxo",
    ["fq"] = "FlyQuest",
    ["fntc"] = "Fnatic",
    ["forz"] = "FORZE Esports",
    ["furi"] = "FURIA Esports",	
    ["g2"] = "G2 Esports",
    ["gamb"] = "Gambit Esports",
    ["gl"] = "Team GamerLegion",
    ["god"] = "GODSENT",
    ["gray"] = "Grayhound Gaming",
    ["hlr"] = "HellRaisers",
    ["hero"] = "Heroic",
    ["ibp"] = "Team iBUYPOWER",
    ["ihc"] = "IHC Esports",
    ["imt"] = "Immortals",
    ["im"] = "Team Immunity",
    ["imp"] = "Imperial Esports",
    ["itb"] = "Into The Breach",
    ["intz"] = "INTZ eSports",
    ["keyd"] = "Keyd Stars",
    ["king"] = "Team Кinguin",
    ["koi"] = "KOI",
    ["ldlc"] = "Team LDLC.com",
    ["lgcy"] = "Legacy",
    ["lgb"] = "LGB eSports",
    ["liq"] = "Team Liquid",
    ["lc"] = "London Conspiracy",
    ["lumi"] = "Luminosity Gaming",
    ["lynn"] = "Lynn Vision Gaming",
    ["mibr"] = "MIBR",
    ["mfg"] = "Misfits",
    ["mngz"] = "The MongolZ",
    ["mont"] = "Monte",
    ["mss"] = "mousesports",
    ["mouz"] = "MOUZ",
    ["ride"] = "Movistar Riders",
    ["myxmg"] = "myXMG",
    ["nf"] = "n!faculty",
    ["navi"] = "Natus Vincere",
    ["nip"] = "Ninjas in Pyjamas",
    ["nor"] = "North",
    ["nrg"] = "NRG Esports",
    ["og"] = "OG",
    ["optc"] = "OpTic Gaming",
    ["orbit"] = "Orbit Esport",
    ["out"] = "Outsiders",	
    ["pain"] = "paiN Gaming",
    ["psnu"] = "Passion UA",
    ["penta"] = "PENTA Sports",
    ["pkd"] = "Planetkey Dynamics",	
    ["qb"] = "Quantum Bellator Fire",
    ["ratm"] = "Rare Atom",
    ["rgg"] = "Reason Gaming",
    ["wgg"] = "Recursive eSports",
    ["ren"] = "Renegades",
    ["rog"] = "Rogue",
    ["saw"] = "SAW",
    ["shrk"] = "Sharks Esports",
    ["sk"] = "SK Gaming",
    ["spc"] = "Space Soldiers",
    ["spir"] = "Team Spirit",
    ["splc"] = "Splyce",
    ["spr"] = "Sprout",
    ["syma"] = "Syman Gamingf",
    ["tsm"] = "Team SoloMid",
    ["tit"] = "Titan",
    ["tyl"] = "Tyloo",	
    ["us"] = "Universal Soldiers",
    ["vega"] = "Vega Squadron",
    ["vg"] = "VeryGames",
    ["vex"] = "Vexed Gaming",
    ["vici"] = "ViCi Gaming",
    ["vp"] = "Virtus.Pro",
    ["vita"] = "Team Vitality",
    ["ve"] = "Vox Eminor",	
    ["wins"] = "Winstrike Team",
    ["wcrd"] = "Wildcard",
    ["indw"] = "Team Wolf",	
    ["e6ten"] = "x6tence",
    ["xapso"] = "Xapso"
}

local random = math.random

AddEventHandler("OnMapLoad", function(event)
    local random_1 = random(1, #teams)
    local team_1 = teams[random_1]
    local teamName_1 = teamsName[team_1]
    server:Execute("mp_teamlogo_1 " .. team_1)
    server:Execute("mp_teamname_1 " .. teamName_1)
    local random_2 = random(1, #teams)
    local team_2 = teams[random_2]
    local teamName_2 = teamsName[team_2]
    server:Execute("mp_teamlogo_2 " .. team_2)
    server:Execute("mp_teamname_2 " .. teamName_2)
end)
